"""add mail

Revision ID: de63b0bd8232
Revises: bfeec00e1c76
Create Date: 2023-12-08 01:53:08.055006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de63b0bd8232'
down_revision: Union[str, None] = 'bfeec00e1c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mail', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['mail'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'mail')
    # ### end Alembic commands ###
