"""2

Revision ID: 6ce4e7cbfcfd
Revises: 3c285ea08897
Create Date: 2023-11-22 13:32:50.110816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ce4e7cbfcfd'
down_revision: Union[str, None] = '3c285ea08897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'description')
    # ### end Alembic commands ###
