"""3

Revision ID: bfeec00e1c76
Revises: 6ce4e7cbfcfd
Create Date: 2023-11-27 22:34:27.672452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfeec00e1c76'
down_revision: Union[str, None] = '6ce4e7cbfcfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'is_active')
    # ### end Alembic commands ###
